### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by WyattHuang1** [roncoo/roncoo-education-web#1]
首先感谢你们开源了这么牛逼的一个网课平台！
以下提一些我对网站不成熟的小建议：

1. 把 **登陆 | 注册** 做成有颜色的圆角矩形按钮放在导航栏的右边，而不要因为这两个按钮而在网站上方留一个黑色的条条
2. 美化一下主页面那个class 是 `left_block` 的UI
3. 新增一个博客功能，以便让用户看到平台的最新动态

**Comment by mrvon2015** [comment]
感谢你的建议，会考虑做优化！
